# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  version "0.1.54"

  on_macos do
    on_intel do
      sha256 "2e1d47a1df0774ba94482f89ee27ccc43af9e320375062025f2f44c114e294d4"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "120d59aa35246d8bdcef64cd6a2f56c6690437fe17b201fad791137626eb0465"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "617d7be4dfeaf28cbe6d758b4729716f583709bb05094a8053581287c98f1d0c"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "710c636e568b55dde008393724f6f53497716a4376b74c51b70d6f391da0f548"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
    end
  end

  name "ward"
  desc "Hierarchical secrets manager"
  homepage "https://github.com/br4zz4/ward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
