# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  version "0.1.6"

  on_macos do
    on_intel do
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
      sha256 "e2f2bf9b14296a946bc2a081f3284d5384bbafed2166bec412ff33d7501fa196"
    end
    on_arm do
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
      sha256 "8676cff3bdf0ae8f1b81d4ff633832d95364f38a12e99916f4e237b1a937777e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
      sha256 "74f6721d3a800bc0366b7ecb476278e57b6c3b62c955d74f9931381622a174be"
    end
    on_arm do
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
      sha256 "c9036db6250bf71cb2d9b478fd5e05ca4763dd029211abc110cecaf25cbaaf40"
    end
  end

  name "ward"
  desc "Hierarchical secrets management using SOPS+age."
  homepage "https://github.com/oporpino/ward"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "age",
      "sops",
    ]

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
