# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  version "0.1.20"

  on_macos do
    on_intel do
      sha256 "abc7a3e9cbe2bde1e578d96144f5809a879b05cf3dc198d8adb82afb0c77728b"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8438df8cb7ce8a044c7ef142f8c78cee78169a9d95d01f6087760490f96db59a"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c5e5e7f3418d935216402e406fed192cfb98860f92695c15700bcd5cbd0f6b1"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f72209427e6fa636661f2df29dbea29d705eec49cfa290b89757c4089d34d491"
      url "https://github.com/oporpino/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
    end
  end

  name "ward"
  desc "Hierarchical secrets management using SOPS+age."
  homepage "https://github.com/oporpino/ward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
